### ISSUE TITLE
__main__.py instead of hfinger.py

### ISSUE THREAD

**Issue by ventaquil** [CERT-Polska/hfinger#2]
Consider moving `hfinger.py` file to `hfinger/__main__.py` to give possibility to execute hfinger using `-m` flag.

    $ python3 -m hfinger ...

You should add one extra parameter to deliver program name

    my_parser = argparse.ArgumentParser(
        description="Hfinger - fingerprinting HTTP requests stored in pcap files",
        allow_abbrev=False,
        prog="hfinger",  # <- this one
    )

Without change

    $ python3 -m hfinger
    usage: __main__.py [-h] (-f FILE | -d DIR) [-o output_path] [-m {0,1,2}]
    __main__.py: error: one of the arguments -f/--file -d/--directory is required

After change

    $ python3 -m hfinger
    usage: hfinger [-h] (-f FILE | -d DIR) [-o output_path] [-m {0,1,2}]
    hfinger: error: one of the arguments -f/--file -d/--directory is required

**Comment by PBia** [comment]
Hi, thanks for the info. We plan to add better modularity support of _hfinger_ - maybe in the next release.

**Comment by ventaquil** [comment]
Nice - waiting for it 👍

**Comment by PBia** [comment]
Hi, sorry for keeping you waiting. Now everything should work as you pointed out plus we have added additional report modes. You can find more info in the [changelog](https://github.com/CERT-Polska/hfinger/blob/master/CHANGELOG). Please open an issue if something is wrong.

**Comment by ventaquil** [comment]
Don't worry, nice to see that project is growing. Everything is looks okay now for me.
